FROM golang:stretch

RUN mkdir -p src/k8s.io
WORKDIR $GOPATH/src/k8s.io
RUN git clone https://github.com/kubernetes/code-generator --depth=1 -b release-1.9
RUN ls
WORKDIR $GOPATH
RUN env
ENV GOARC amd64
ENV CGO 0

ENV GOOS darwin
RUN mkdir -p bin/darwin
RUN go build -o bin/darwin/client-gen k8s.io/code-generator/cmd/client-gen
RUN go build -o bin/darwin/conversion-gen k8s.io/code-generator/cmd/conversion-gen
RUN go build -o bin/darwin/deepcopy-gen k8s.io/code-generator/cmd/deepcopy-gen
RUN go build -o bin/darwin/defaulter-gen k8s.io/code-generator/cmd/defaulter-gen
RUN go build -o bin/darwin/informer-gen k8s.io/code-generator/cmd/informer-gen
RUN go build -o bin/darwin/lister-gen k8s.io/code-generator/cmd/lister-gen
RUN go build -o bin/darwin/openapi-gen k8s.io/code-generator/cmd/openapi-gen

ENV GOOS linux
RUN mkdir -p bin/linux
RUN go build -o bin/linux/client-gen k8s.io/code-generator/cmd/client-gen
RUN go build -o bin/linux/conversion-gen k8s.io/code-generator/cmd/conversion-gen
RUN go build -o bin/linux/deepcopy-gen k8s.io/code-generator/cmd/deepcopy-gen
RUN go build -o bin/linux/defaulter-gen k8s.io/code-generator/cmd/defaulter-gen
RUN go build -o bin/linux/informer-gen k8s.io/code-generator/cmd/informer-gen
RUN go build -o bin/linux/lister-gen k8s.io/code-generator/cmd/lister-gen
RUN go build -o bin/linux/openapi-gen k8s.io/code-generator/cmd/openapi-gen

