/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1 "sigs.k8s.io/apiserver-builder-alpha/example/podlogs/pkg/apis/podlogs/v1"
	scheme "sigs.k8s.io/apiserver-builder-alpha/example/podlogs/pkg/client/clientset_generated/clientset/scheme"
)

// PodLogsesGetter has a method to return a PodLogsInterface.
// A group's client should implement this interface.
type PodLogsesGetter interface {
	PodLogses(namespace string) PodLogsInterface
}

// PodLogsInterface has methods to work with PodLogs resources.
type PodLogsInterface interface {
	Create(*v1.PodLogs) (*v1.PodLogs, error)
	Update(*v1.PodLogs) (*v1.PodLogs, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.PodLogs, error)
	List(opts metav1.ListOptions) (*v1.PodLogsList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.PodLogs, err error)
	PodLogsExpansion
}

// podLogses implements PodLogsInterface
type podLogses struct {
	client rest.Interface
	ns     string
}

// newPodLogses returns a PodLogses
func newPodLogses(c *PodlogsV1Client, namespace string) *podLogses {
	return &podLogses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the podLogs, and returns the corresponding podLogs object, and an error if there is any.
func (c *podLogses) Get(name string, options metav1.GetOptions) (result *v1.PodLogs, err error) {
	result = &v1.PodLogs{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("podlogses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PodLogses that match those selectors.
func (c *podLogses) List(opts metav1.ListOptions) (result *v1.PodLogsList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.PodLogsList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("podlogses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested podLogses.
func (c *podLogses) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("podlogses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a podLogs and creates it.  Returns the server's representation of the podLogs, and an error, if there is any.
func (c *podLogses) Create(podLogs *v1.PodLogs) (result *v1.PodLogs, err error) {
	result = &v1.PodLogs{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("podlogses").
		Body(podLogs).
		Do().
		Into(result)
	return
}

// Update takes the representation of a podLogs and updates it. Returns the server's representation of the podLogs, and an error, if there is any.
func (c *podLogses) Update(podLogs *v1.PodLogs) (result *v1.PodLogs, err error) {
	result = &v1.PodLogs{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("podlogses").
		Name(podLogs.Name).
		Body(podLogs).
		Do().
		Into(result)
	return
}

// Delete takes name of the podLogs and deletes it. Returns an error if one occurs.
func (c *podLogses) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("podlogses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *podLogses) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("podlogses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched podLogs.
func (c *podLogses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.PodLogs, err error) {
	result = &v1.PodLogs{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("podlogses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
