language: go

go:
- 1.13.2

go_import_path: sigs.k8s.io/apiserver-builder-alpha

cache:
  directories:
  - /usr/local/kubebuilder
  - /home/travis/.cache/bazel

git:
  depth: 3

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.29.1/bazel_0.29.1-linux-x86_64.deb
  - sudo dpkg -i bazel_0.29.1-linux-x86_64.deb
  - scripts/install_etcd.sh
  - test/install-kubebuilder.sh

install:
  - make install

jobs:
  include:
    - stage: Test Example
      env: TEST=example
      script: sudo env "PATH=$PATH" ./test/travis.sh

    - stage: Test New Project
      env: TEST=test
      script: sudo env "PATH=$PATH" ./test/travis.sh
