/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	podlogsv1 "sigs.k8s.io/apiserver-builder-alpha/example/podlogs/pkg/apis/podlogs/v1"
)

// FakePodLogses implements PodLogsInterface
type FakePodLogses struct {
	Fake *FakePodlogsV1
	ns   string
}

var podlogsesResource = schema.GroupVersionResource{Group: "podlogs.example.com", Version: "v1", Resource: "podlogses"}

var podlogsesKind = schema.GroupVersionKind{Group: "podlogs.example.com", Version: "v1", Kind: "PodLogs"}

// Get takes name of the podLogs, and returns the corresponding podLogs object, and an error if there is any.
func (c *FakePodLogses) Get(name string, options v1.GetOptions) (result *podlogsv1.PodLogs, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(podlogsesResource, c.ns, name), &podlogsv1.PodLogs{})

	if obj == nil {
		return nil, err
	}
	return obj.(*podlogsv1.PodLogs), err
}

// List takes label and field selectors, and returns the list of PodLogses that match those selectors.
func (c *FakePodLogses) List(opts v1.ListOptions) (result *podlogsv1.PodLogsList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(podlogsesResource, podlogsesKind, c.ns, opts), &podlogsv1.PodLogsList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*podlogsv1.PodLogsList), err
}

// Watch returns a watch.Interface that watches the requested podLogses.
func (c *FakePodLogses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(podlogsesResource, c.ns, opts))

}

// Create takes the representation of a podLogs and creates it.  Returns the server's representation of the podLogs, and an error, if there is any.
func (c *FakePodLogses) Create(podLogs *podlogsv1.PodLogs) (result *podlogsv1.PodLogs, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(podlogsesResource, c.ns, podLogs), &podlogsv1.PodLogs{})

	if obj == nil {
		return nil, err
	}
	return obj.(*podlogsv1.PodLogs), err
}

// Update takes the representation of a podLogs and updates it. Returns the server's representation of the podLogs, and an error, if there is any.
func (c *FakePodLogses) Update(podLogs *podlogsv1.PodLogs) (result *podlogsv1.PodLogs, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(podlogsesResource, c.ns, podLogs), &podlogsv1.PodLogs{})

	if obj == nil {
		return nil, err
	}
	return obj.(*podlogsv1.PodLogs), err
}

// Delete takes name of the podLogs and deletes it. Returns an error if one occurs.
func (c *FakePodLogses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(podlogsesResource, c.ns, name), &podlogsv1.PodLogs{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePodLogses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(podlogsesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &podlogsv1.PodLogsList{})
	return err
}

// Patch applies the patch and returns the patched podLogs.
func (c *FakePodLogses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *podlogsv1.PodLogs, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(podlogsesResource, c.ns, name, pt, data, subresources...), &podlogsv1.PodLogs{})

	if obj == nil {
		return nil, err
	}
	return obj.(*podlogsv1.PodLogs), err
}
