/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by apiregister-gen. Do not edit it manually!

package sharedinformers

import (
	"github.com/kubernetes-incubator/apiserver-builder-example/pkg/client/clientset_generated/clientset"
	"github.com/kubernetes-incubator/apiserver-builder-example/pkg/client/informers_generated/externalversions"
	"github.com/kubernetes-incubator/apiserver-builder/pkg/controller"
	"k8s.io/client-go/rest"
	"time"
)

// SharedInformers wraps all informers used by controllers so that
// they are shared across controller implementations
type SharedInformers struct {
	controller.SharedInformersDefaults
	Factory externalversions.SharedInformerFactory
}

// newSharedInformers returns a set of started informers
func NewSharedInformers(config *rest.Config, shutdown <-chan struct{}) *SharedInformers {
	si := &SharedInformers{
		controller.SharedInformersDefaults{},
		externalversions.NewSharedInformerFactory(clientset.NewForConfigOrDie(config), 10*time.Minute),
	}
	if si.SetupKubernetesTypes() {
		si.InitKubernetesInformers(config)
	}
	si.Init()
	si.startInformers(shutdown)
	si.StartAdditionalInformers(shutdown)
	return si
}

// startInformers starts all of the informers
func (si *SharedInformers) startInformers(shutdown <-chan struct{}) {
	go si.Factory.Simple().V1alpha1().MyControllers().Informer().Run(shutdown)
}
