// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	simple "github.com/kubernetes-incubator/apiserver-builder-example/pkg/apis/simple"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_MyController_To_simple_MyController,
		Convert_simple_MyController_To_v1alpha1_MyController,
		Convert_v1alpha1_MyControllerList_To_simple_MyControllerList,
		Convert_simple_MyControllerList_To_v1alpha1_MyControllerList,
		Convert_v1alpha1_MyControllerSpec_To_simple_MyControllerSpec,
		Convert_simple_MyControllerSpec_To_v1alpha1_MyControllerSpec,
		Convert_v1alpha1_MyControllerStatus_To_simple_MyControllerStatus,
		Convert_simple_MyControllerStatus_To_v1alpha1_MyControllerStatus,
		Convert_v1alpha1_MyControllerStatusStrategy_To_simple_MyControllerStatusStrategy,
		Convert_simple_MyControllerStatusStrategy_To_v1alpha1_MyControllerStatusStrategy,
		Convert_v1alpha1_MyControllerStrategy_To_simple_MyControllerStrategy,
		Convert_simple_MyControllerStrategy_To_v1alpha1_MyControllerStrategy,
	)
}

func autoConvert_v1alpha1_MyController_To_simple_MyController(in *MyController, out *simple.MyController, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_MyControllerSpec_To_simple_MyControllerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_MyControllerStatus_To_simple_MyControllerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_MyController_To_simple_MyController is an autogenerated conversion function.
func Convert_v1alpha1_MyController_To_simple_MyController(in *MyController, out *simple.MyController, s conversion.Scope) error {
	return autoConvert_v1alpha1_MyController_To_simple_MyController(in, out, s)
}

func autoConvert_simple_MyController_To_v1alpha1_MyController(in *simple.MyController, out *MyController, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_simple_MyControllerSpec_To_v1alpha1_MyControllerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_simple_MyControllerStatus_To_v1alpha1_MyControllerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_simple_MyController_To_v1alpha1_MyController is an autogenerated conversion function.
func Convert_simple_MyController_To_v1alpha1_MyController(in *simple.MyController, out *MyController, s conversion.Scope) error {
	return autoConvert_simple_MyController_To_v1alpha1_MyController(in, out, s)
}

func autoConvert_v1alpha1_MyControllerList_To_simple_MyControllerList(in *MyControllerList, out *simple.MyControllerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]simple.MyController)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_MyControllerList_To_simple_MyControllerList is an autogenerated conversion function.
func Convert_v1alpha1_MyControllerList_To_simple_MyControllerList(in *MyControllerList, out *simple.MyControllerList, s conversion.Scope) error {
	return autoConvert_v1alpha1_MyControllerList_To_simple_MyControllerList(in, out, s)
}

func autoConvert_simple_MyControllerList_To_v1alpha1_MyControllerList(in *simple.MyControllerList, out *MyControllerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items == nil {
		out.Items = make([]MyController, 0)
	} else {
		out.Items = *(*[]MyController)(unsafe.Pointer(&in.Items))
	}
	return nil
}

// Convert_simple_MyControllerList_To_v1alpha1_MyControllerList is an autogenerated conversion function.
func Convert_simple_MyControllerList_To_v1alpha1_MyControllerList(in *simple.MyControllerList, out *MyControllerList, s conversion.Scope) error {
	return autoConvert_simple_MyControllerList_To_v1alpha1_MyControllerList(in, out, s)
}

func autoConvert_v1alpha1_MyControllerSpec_To_simple_MyControllerSpec(in *MyControllerSpec, out *simple.MyControllerSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_MyControllerSpec_To_simple_MyControllerSpec is an autogenerated conversion function.
func Convert_v1alpha1_MyControllerSpec_To_simple_MyControllerSpec(in *MyControllerSpec, out *simple.MyControllerSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MyControllerSpec_To_simple_MyControllerSpec(in, out, s)
}

func autoConvert_simple_MyControllerSpec_To_v1alpha1_MyControllerSpec(in *simple.MyControllerSpec, out *MyControllerSpec, s conversion.Scope) error {
	return nil
}

// Convert_simple_MyControllerSpec_To_v1alpha1_MyControllerSpec is an autogenerated conversion function.
func Convert_simple_MyControllerSpec_To_v1alpha1_MyControllerSpec(in *simple.MyControllerSpec, out *MyControllerSpec, s conversion.Scope) error {
	return autoConvert_simple_MyControllerSpec_To_v1alpha1_MyControllerSpec(in, out, s)
}

func autoConvert_v1alpha1_MyControllerStatus_To_simple_MyControllerStatus(in *MyControllerStatus, out *simple.MyControllerStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_MyControllerStatus_To_simple_MyControllerStatus is an autogenerated conversion function.
func Convert_v1alpha1_MyControllerStatus_To_simple_MyControllerStatus(in *MyControllerStatus, out *simple.MyControllerStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_MyControllerStatus_To_simple_MyControllerStatus(in, out, s)
}

func autoConvert_simple_MyControllerStatus_To_v1alpha1_MyControllerStatus(in *simple.MyControllerStatus, out *MyControllerStatus, s conversion.Scope) error {
	return nil
}

// Convert_simple_MyControllerStatus_To_v1alpha1_MyControllerStatus is an autogenerated conversion function.
func Convert_simple_MyControllerStatus_To_v1alpha1_MyControllerStatus(in *simple.MyControllerStatus, out *MyControllerStatus, s conversion.Scope) error {
	return autoConvert_simple_MyControllerStatus_To_v1alpha1_MyControllerStatus(in, out, s)
}

func autoConvert_v1alpha1_MyControllerStatusStrategy_To_simple_MyControllerStatusStrategy(in *MyControllerStatusStrategy, out *simple.MyControllerStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_MyControllerStatusStrategy_To_simple_MyControllerStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_MyControllerStatusStrategy_To_simple_MyControllerStatusStrategy(in *MyControllerStatusStrategy, out *simple.MyControllerStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_MyControllerStatusStrategy_To_simple_MyControllerStatusStrategy(in, out, s)
}

func autoConvert_simple_MyControllerStatusStrategy_To_v1alpha1_MyControllerStatusStrategy(in *simple.MyControllerStatusStrategy, out *MyControllerStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_simple_MyControllerStatusStrategy_To_v1alpha1_MyControllerStatusStrategy is an autogenerated conversion function.
func Convert_simple_MyControllerStatusStrategy_To_v1alpha1_MyControllerStatusStrategy(in *simple.MyControllerStatusStrategy, out *MyControllerStatusStrategy, s conversion.Scope) error {
	return autoConvert_simple_MyControllerStatusStrategy_To_v1alpha1_MyControllerStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_MyControllerStrategy_To_simple_MyControllerStrategy(in *MyControllerStrategy, out *simple.MyControllerStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_MyControllerStrategy_To_simple_MyControllerStrategy is an autogenerated conversion function.
func Convert_v1alpha1_MyControllerStrategy_To_simple_MyControllerStrategy(in *MyControllerStrategy, out *simple.MyControllerStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_MyControllerStrategy_To_simple_MyControllerStrategy(in, out, s)
}

func autoConvert_simple_MyControllerStrategy_To_v1alpha1_MyControllerStrategy(in *simple.MyControllerStrategy, out *MyControllerStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_simple_MyControllerStrategy_To_v1alpha1_MyControllerStrategy is an autogenerated conversion function.
func Convert_simple_MyControllerStrategy_To_v1alpha1_MyControllerStrategy(in *simple.MyControllerStrategy, out *MyControllerStrategy, s conversion.Scope) error {
	return autoConvert_simple_MyControllerStrategy_To_v1alpha1_MyControllerStrategy(in, out, s)
}
