/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by apiregister-gen. Do not edit it manually!

package simple

import (
	"fmt"
	"github.com/kubernetes-incubator/apiserver-builder/pkg/builders"
	"k8s.io/apimachinery/pkg/apis/meta/internalversion"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apiserver/pkg/endpoints/request"
	"k8s.io/apiserver/pkg/registry/rest"
)

var (
	InternalMyController = builders.NewInternalResource(
		"mycontrollers",
		func() runtime.Object { return &MyController{} },
		func() runtime.Object { return &MyControllerList{} },
	)
	InternalMyControllerStatus = builders.NewInternalResourceStatus(
		"mycontrollers",
		func() runtime.Object { return &MyController{} },
		func() runtime.Object { return &MyControllerList{} },
	)
	// Registered resources and subresources
	ApiVersion = builders.NewApiGroup("simple.example.com").WithKinds(
		InternalMyController,
		InternalMyControllerStatus,
	)

	// Required by code generated by go2idl
	AddToScheme        = ApiVersion.SchemaBuilder.AddToScheme
	SchemeBuilder      = ApiVersion.SchemaBuilder
	localSchemeBuilder = &SchemeBuilder
	SchemeGroupVersion = ApiVersion.GroupVersion
)

// Required by code generated by go2idl
// Kind takes an unqualified kind and returns a Group qualified GroupKind
func Kind(kind string) schema.GroupKind {
	return SchemeGroupVersion.WithKind(kind).GroupKind()
}

// Required by code generated by go2idl
// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}

// +genclient=true
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type MyController struct {
	metav1.TypeMeta
	metav1.ObjectMeta
	Spec   MyControllerSpec
	Status MyControllerStatus
}

type MyControllerSpec struct {
}

type MyControllerStatus struct {
}

//
// MyController Functions and Structs
//
// +k8s:deepcopy-gen=false
type MyControllerStrategy struct {
	builders.DefaultStorageStrategy
}

// +k8s:deepcopy-gen=false
type MyControllerStatusStrategy struct {
	builders.DefaultStatusStorageStrategy
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type MyControllerList struct {
	metav1.TypeMeta
	metav1.ListMeta
	Items []MyController
}

func (MyController) NewStatus() interface{} {
	return MyControllerStatus{}
}

func (pc *MyController) GetStatus() interface{} {
	return pc.Status
}

func (pc *MyController) SetStatus(s interface{}) {
	pc.Status = s.(MyControllerStatus)
}

func (pc *MyController) GetSpec() interface{} {
	return pc.Spec
}

func (pc *MyController) SetSpec(s interface{}) {
	pc.Spec = s.(MyControllerSpec)
}

func (pc *MyController) GetObjectMeta() *metav1.ObjectMeta {
	return &pc.ObjectMeta
}

func (pc *MyController) SetGeneration(generation int64) {
	pc.ObjectMeta.Generation = generation
}

func (pc MyController) GetGeneration() int64 {
	return pc.ObjectMeta.Generation
}

// Registry is an interface for things that know how to store MyController.
// +k8s:deepcopy-gen=false
type MyControllerRegistry interface {
	ListMyControllers(ctx request.Context, options *internalversion.ListOptions) (*MyControllerList, error)
	GetMyController(ctx request.Context, id string, options *metav1.GetOptions) (*MyController, error)
	CreateMyController(ctx request.Context, id *MyController) (*MyController, error)
	UpdateMyController(ctx request.Context, id *MyController) (*MyController, error)
	DeleteMyController(ctx request.Context, id string) (bool, error)
}

// NewRegistry returns a new Registry interface for the given Storage. Any mismatched types will panic.
func NewMyControllerRegistry(sp builders.StandardStorageProvider) MyControllerRegistry {
	return &storageMyController{sp}
}

// Implement Registry
// storage puts strong typing around storage calls
// +k8s:deepcopy-gen=false
type storageMyController struct {
	builders.StandardStorageProvider
}

func (s *storageMyController) ListMyControllers(ctx request.Context, options *internalversion.ListOptions) (*MyControllerList, error) {
	if options != nil && options.FieldSelector != nil && !options.FieldSelector.Empty() {
		return nil, fmt.Errorf("field selector not supported yet")
	}
	st := s.GetStandardStorage()
	obj, err := st.List(ctx, options)
	if err != nil {
		return nil, err
	}
	return obj.(*MyControllerList), err
}

func (s *storageMyController) GetMyController(ctx request.Context, id string, options *metav1.GetOptions) (*MyController, error) {
	st := s.GetStandardStorage()
	obj, err := st.Get(ctx, id, options)
	if err != nil {
		return nil, err
	}
	return obj.(*MyController), nil
}

func (s *storageMyController) CreateMyController(ctx request.Context, object *MyController) (*MyController, error) {
	st := s.GetStandardStorage()
	obj, err := st.Create(ctx, object, false)
	if err != nil {
		return nil, err
	}
	return obj.(*MyController), nil
}

func (s *storageMyController) UpdateMyController(ctx request.Context, object *MyController) (*MyController, error) {
	st := s.GetStandardStorage()
	obj, _, err := st.Update(ctx, object.Name, rest.DefaultUpdatedObjectInfo(object, builders.Scheme))
	if err != nil {
		return nil, err
	}
	return obj.(*MyController), nil
}

func (s *storageMyController) DeleteMyController(ctx request.Context, id string) (bool, error) {
	st := s.GetStandardStorage()
	_, sync, err := st.Delete(ctx, id, nil)
	return sync, err
}
