/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	podlogsv1 "sigs.k8s.io/apiserver-builder-alpha/example/podlogs/pkg/apis/podlogs/v1"
	clientset "sigs.k8s.io/apiserver-builder-alpha/example/podlogs/pkg/client/clientset_generated/clientset"
	internalinterfaces "sigs.k8s.io/apiserver-builder-alpha/example/podlogs/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1 "sigs.k8s.io/apiserver-builder-alpha/example/podlogs/pkg/client/listers_generated/podlogs/v1"
)

// PodLogsInformer provides access to a shared informer and lister for
// PodLogses.
type PodLogsInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.PodLogsLister
}

type podLogsInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPodLogsInformer constructs a new informer for PodLogs type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPodLogsInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPodLogsInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPodLogsInformer constructs a new informer for PodLogs type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPodLogsInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PodlogsV1().PodLogses(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PodlogsV1().PodLogses(namespace).Watch(options)
			},
		},
		&podlogsv1.PodLogs{},
		resyncPeriod,
		indexers,
	)
}

func (f *podLogsInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPodLogsInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *podLogsInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&podlogsv1.PodLogs{}, f.defaultInformer)
}

func (f *podLogsInformer) Lister() v1.PodLogsLister {
	return v1.NewPodLogsLister(f.Informer().GetIndexer())
}
